<?php





function showWiz()
{

       extract($_POST);

       echo "
       <div class='kt-heading kt-heading--md'>Review your Details and Submit</div>
       <div class='kt-form__section kt-form__section--first'>
           <div class='kt-wizard-v4__review'>
               <div class='kt-wizard-v4__review-item'>
                   <div class='kt-wizard-v4__review-title'>
                       <!--Member's full name and COPrID here--> 
                   </div>
                   <div class='kt-wizard-v4__review-content'>
                       <br/> first Name: ".$fname."
                       <br/> last Name : ".$lname."
                       <br/> Other Names: ".$oname."
                       <br/> Phone:".$contact."
                       <br/> Email: ".$email."
                   </div>
               </div>
               <div class='kt-wizard-v4__review-item'>
                   <div class='kt-wizard-v4__review-title'>
                       Your Address Details
                   </div>
                   <div class='kt-wizard-v4__review-content'>
                       Address Line 1: ".$address1."
                       <br/> Address Line 2:".$address2."
                       <br/> Region:".$region."
                       <br/> Country:".$country."
                   </div>
               </div>
               <div class='kt-wizard-v4__review-item'>
                   <div class='kt-wizard-v4__review-title'>
                       Chosen Assembly
                   </div>
                   <div class='kt-wizard-v4__review-content'>
                    
                     <!--print a short receipt notice for member-->
                       <br/> Assembly: ".$assembly."
                       <br/> Ministry: ".$ministry."
                       <br/>Group: ".$group."
                      
                   </div>
               </div>

               <div class='kt-wizard-v4__review-item'>
                   <div class='kt-wizard-v4__review-title'>
                       Your Login Credentials<!--this fields are autogenerated -->
                   </div>
                   <div class='kt-wizard-v4__review-content'>
                       Username: ".$uname."
                       <br/> Password: ".$pass."
                       <br /> <span id='memurl'>Member url:</span>
                       <br/> QR Code: <!--generate qr code here-->
                      
                   </div>
               </div>
           </div>
       </div>
   ";
}



function SubmitForms()
{


       include 'db.php';

       $cop = rand(0,99999);
       $dor = date('d/m/y, h:m:s');
       extract($_POST);
       $error = false;

       if(strlen($pass) < 6)
       {
        $error = true;
        echo  "Oops Password too short !! ";
       }
       if($pass != $cpass){
        $error = true;
        echo  "Oops Passwords do not match !!";
       }
       if (empty($contact)) {
        $error = true;
        echo  "Oops contact  must not be empty !!";
       }
       if (!$error) {
              if (mysqli_query($con,"INSERT INTO users(
                     fname,lname,onames,dob,gender,Occupation,
                     contactphone,otherphone,email,cop,assembly,
                     ministry,groups,baptism,dobaptism,residence,
                     ghid,uname,pass,timezone,all_u_pass,
                     all_u_dash,addr_li_1,addr_li_2,postcode,city,region,
                     country,mothersname,motherscontact,mothersaddress,
                     mothersstatus,fathersname,fatherscontact,fathersaddress,
                     fathersstatus,nok,nokcont,nok_address,marital_status,dor
                     )VALUES('$fname','$lname','$oname','$dob','$gender',
                              '$Occupation','$contact','$ocontact',
                              '$email','$cop','$assembly','$ministry','$group',
                              '$baptism','$dobaptism','$residence','$ghid',
                              '$uname','$pass','$tzone','$all_pass','$all_dash',
                              '$address1','$address2','$postcode','$state','$region',
                              '$country','$mname','$mcontact','$maddress',
                              '$mstat','$fatname','$fcont','$faddress',
                              '$fstat','$nok','$nokcont','$nokaddress','$maritstat','$dor') ")) { 
                                  
                     $_SESSION['uid'] = $cop;

                     echo 'done';


              }else{
                     echo "Oops data could not be uploaded ";
              }
       }









}


function UserInfo($info)
{
    include 'db.php';

    $id = $_SESSION['uid'];

    $fetch = mysqli_query($con,"SELECT * FROM users WHERE cop = '$id' ");

    $row = mysqli_fetch_array($fetch);



    return $row[$info];


}


function age($date)
{
    // 2020-02-07
    $date_of_birth = explode("-",$date);
    $year          = $date_of_birth[0];
   
    $age = date('Y') - $year;

    echo $age;

}



function GetUserInfo($info)
{
        include 'db.php';

        extract($_GET);

        if ($id) {

        $_SESSION['id'] = $id;
           
        $fetch = mysqli_query($con,"SELECT * FROM users WHERE id = '$id'  ");

        $row = mysqli_fetch_array($fetch);


        return $row[$info];



       }






}



function UpdateUserInfo()
{
      include 'db.php';

      extract($_POST);
      
      $id = $_SESSION['id'];

      if(mysqli_query($con,"UPDATE users SET cop='$accnum',email='$email', language='$language',timezone='$timezone' WHERE id = '$id' ")){
          echo 'done';
      }else{
          echo "Oops could not update";
      }


}



function Deactivate()
{

    include 'db.php';
     $value = $_POST['data'];
     $id = $_SESSION['id'];

     if(mysqli_query($con,"UPDATE users SET statuses='$value' WHERE id = '$id' ")){

        echo 'done';

    }else{
        echo "Oops could not update";
    }




}



function UpdatePass()
{
    include 'db.php';

    extract($_POST);
    
    $id = $_SESSION['id'];
    $error = false;

    $check = mysqli_query($con,"SELECT * FROM users  WHERE id = '$id' ");
    $row = mysqli_fetch_array($check);

    if ($npass != $vpass) {
        $error = true;
        echo 'Oops passwords do not match ';
    }
    if (!$error) {
        if ($cupass == $row['pass']) {

            if(mysqli_query($con,"UPDATE users SET pass='$npass' WHERE id = '$id' ")){
    
                echo 'done';
            }else{
                echo "Oops could not update";
            }
        }else{
               echo "Oops your Current password is not not correct";
        }
    }
    


    
}